### ISSUE TITLE
No keyboard to login

### ISSUE THREAD

**Issue by MajorGeek** [ArtanisInc/Post-Tweaks#14] opened 2022-04-07 11:39 UTC
While testing, I was very conservative, and after a reboot, my keyboard was unresponsive, and I could not log into Windows, meaning I was locked out. Luckily, I was in VMware, or I'd be pissed. Whatever you're doing to mess with Windows login, stop it.

**Comment by DDL56x** [comment] 2022-04-07 22:11
While downloading your latest version 2.1.3 (03/04/2022), Virus Total's AV vendor scans found 4 potential risks of malware as linked:

https://www.virustotal.com/gui/file/7a8822ec371f180a6aee533a124db17c790ee9a623d0444aede89cd4b581deaf

**Comment by ArtanisInc** [comment] 2022-04-09 15:01
Please accept my sincere apologies for the inconvenience caused.
The problem is related to the "msisadrv" driver service, The script disable this service only if a desktop computer is detected, but it does not work with a VM environment.
I will update the script very soon.

**Comment by ArtanisInc** [comment] 2022-04-10 15:38
The problem has been fixed with the new version

**Closed by ArtanisInc** 2022-04-10 15:38 UTC

**Comment by MajorGeek** [comment] 2022-04-10 15:45
Excellent, I'll give it a try now.
